name: Template-Plugin-IO-All
version: 0.01
abstract: Perl Template Toolkit Plugin for IO::All
author: Yung-chung Lin <xern@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Template: 0
  IO::All: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
